[package]
name = "fishnet"
version = "2.0.0-alpha" # remember to update changelog
description = "Distributed Stockfish analysis for lichess.org"
repository = "https://github.com/niklasf/fishnet-alpha"
readme = "README.md"
license = "GPL-3.0+"
authors = ["Niklas Fiekas <niklas.fiekas@backscattering.de>"]
categories = ["command-line-utilities", "web-programming::http-client", "games"]
keywords = ["chess"]
edition = "2018"

[dependencies]
configparser = "1.0"
structopt = "0.3"
#futures = "0.3"
tokio = { version = "0.3", features = ["full"] } # TODO: consider reducing features
url = "2.2"
