[package]
name = "fishnet"
version = "2.0.0-alpha" # remember to update changelog
description = "Distributed Stockfish analysis for lichess.org"
repository = "https://github.com/niklasf/fishnet-alpha"
readme = "README.md"
license = "GPL-3.0+"
authors = ["Niklas Fiekas <niklas.fiekas@backscattering.de>"]
categories = ["command-line-utilities", "web-programming::http-client", "games"]
keywords = ["chess"]
edition = "2018"

[dependencies]
atty = "0.2"
bitflags = "1.2"
configparser = "1.0"
num_cpus = "1.13"
rand = "0.7"
raw-cpuid = "8.1.2"
reqwest = "0.10"
shell-escape = "0.1"
structopt = "0.3"
tempfile = "3.1"
tokio = { version = "0.2", features = ["full"] } # TODO: consider reducing features
tracing = "0.1"
tracing-subscriber = "0.2"
url = "2.2"
