[package]
name = "fishnet"
version = "2.0.1"
description = "Distributed Stockfish analysis for lichess.org"
repository = "https://github.com/niklasf/fishnet"
readme = "README.md"
license = "GPL-3.0+"
authors = ["Niklas Fiekas <niklas.fiekas@backscattering.de>"]
categories = ["command-line-utilities", "web-programming::http-client", "games"]
keywords = ["chess", "lichess"]
edition = "2018"
exclude = ["assets"]

[dependencies]
arrayvec = "0.5"
atty = "0.2"
bitflags = "1.2"
configparser = "1.0"
xz = "0.1"
num_cpus = "1.13"
rand = "0.7"
reqwest = { version = "0.10", features = ["json", "rustls-tls"], default-features = false }
self_update = { version = "0.22", features = ["rustls"], default-features = false }
serde = "1.0"
serde_with = "1.6"
shakmaty = "0.16"
shell-escape = "0.1"
structopt = "0.3"
tempfile = "3.1"
tokio = { version = "0.3", features = ["rt", "macros", "sync", "time", "signal", "process", "io-util"], default-features = false, git = "https://github.com/tokio-rs/tokio.git" }
tokio-compat-02 = "0.1"
url = "2.2"
serde_repr = "0.1"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(target_arch = "x86_64")'.dependencies]
raw-cpuid = "8.1"
