name: Build

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: x86_64-unknown-linux-musl
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --target x86_64-unknown-linux-musl
    - run: mv target/x86_64-unknown-linux-musl/release/fishnet fishnet-linux-x86-64
    - uses: actions/upload-artifact@v2
      with:
        name: fishnet
        path: fishnet-linux-x86-64
